#springdoc:
#  api-docs:
#    path: /api-docs
#    enabled: true
#
#  swagger-ui:
#    path: /docs
#    enabled: true
#    operationsSorter: method
#    tagsSorter: method
# springdoc.swagger-ui.tryItOutEnabled: false
# springdoc.swagger-ui.syntaxHighlight.activated: true
