#springdoc:
#  api-docs:
#    path: /api-docs
#    enabled: true
#
#  swagger-ui:
#    path: /docs
#    enabled: true
#    operationsSorter: method
#    tagsSorter: method
# springdoc.swagger-ui.tryItOutEnabled: false
# springdoc.swagger-ui.syntaxHighlight.activated: true
# springdoc.default-support-form-data: true
# springdoc.pre-loading-enabled: true
# springdoc.api-docs.version: openapi_3_1
springdoc.default-flat-param-object: true
